config/routes.rb
Rails.application.routes.draw do
  
  resources :hometown

  resources :home, path: '/team-roster/'
  root 'home#index'

	resources :players, except: [:destroy] do
		collection { post :import }
		collection { delete :kill }
	end

end

app/models/player.rb
require 'csv'
class Player < ActiveRecord::Base
	
	def self.import(file)
	  CSV.foreach(file.path, headers: true) do |row|
		Player.create! row.to_hash
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@teams = Player.uniq.pluck("team")
  	@notNull = Player.where("hometown IS NOT NULL")
  	
	@homeState = @notNull.group("state").limit(25).order("count_state DESC").count("state")
	@homeCity = @notNull.group("city").limit(25).order("count_city DESC").count("city")

	@pos = @notNull.uniq.pluck("pos")
  end

  def show
  	@players = Player.where("team = ?", params[:id])
  	@playerList = @players.order("pos ASC")
  end
end

app/controllers/hometown_controller.rb
class HometownController < ApplicationController
  def index
  	@players = Player.where("state = ?", params[:id]).order("pos")
  end

  def show
  	@players = Player.where("city = ?", params[:id]).order("pos")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.count
  end

  def import
  	Player.import(params[:file])
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Successful Upload!' }
      format.json { head :no_content }
    end
  end
  
  def show
  	@pos = Player.select("pos", "name", "hometown", "team")
	@players = @pos.where("pos = ?", params[:id])
  end
  
  def create
    @players = @player.count
  end

  def kill
  	@player = Player.all
    @player.each do |t|
    	t.destroy
    end
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Successful Deletion!' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :pos, :hometown, :city, :state, :latitude, :longitude, :team)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hometown_helper.rb
module HometownHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/home/_mapScript.html.erb
<script type="text/javascript">
$(function () {

    // Prepare demo data
    var data = [        
    	{
            "hc-key": "us-ma",
            "value": 0
        },
        {
            "hc-key": "us-wa",
            "value": 1
        },
        {
            "hc-key": "us-ca",
            "value": 2
        },
        {
            "hc-key": "us-or",
            "value": 3
        },
        {
            "hc-key": "us-wi",
            "value": 4
        },
        {
            "hc-key": "us-me",
            "value": 5
        },
        {
            "hc-key": "us-mi",
            "value": 6
        },
        {
            "hc-key": "us-nv",
            "value": 7
        },
        {
            "hc-key": "us-nm",
            "value": 8
        },
        {
            "hc-key": "us-co",
            "value": 9
        },
        {
            "hc-key": "us-wy",
            "value": 10
        },
        {
            "hc-key": "us-ks",
            "value": 11
        },
        {
            "hc-key": "us-ne",
            "value": 12
        },
        {
            "hc-key": "us-ok",
            "value": 13
        },
        {
            "hc-key": "us-mo",
            "value": 14
        },
        {
            "hc-key": "us-il",
            "value": 15
        },
        {
            "hc-key": "us-in",
            "value": 16
        },
        {
            "hc-key": "us-vt",
            "value": 17
        },
        {
            "hc-key": "us-ar",
            "value": 18
        },
        {
            "hc-key": "us-tx",
            "value": 19
        },
        {
            "hc-key": "us-ri",
            "value": 20
        },
        {
            "hc-key": "us-al",
            "value": 21
        },
        {
            "hc-key": "us-ms",
            "value": 22
        },
        {
            "hc-key": "us-nc",
            "value": 23
        },
        {
            "hc-key": "us-va",
            "value": 24
        },
        {
            "hc-key": "us-ia",
            "value": 25
        },
        {
            "hc-key": "us-md",
            "value": 26
        },
        {
            "hc-key": "us-de",
            "value": 27
        },
        {
            "hc-key": "us-pa",
            "value": 28
        },
        {
            "hc-key": "us-nj",
            "value": 29
        },
        {
            "hc-key": "us-ny",
            "value": 30
        },
        {
            "hc-key": "us-id",
            "value": 31
        },
        {
            "hc-key": "us-sd",
            "value": 32
        },
        {
            "hc-key": "us-ct",
            "value": 33
        },
        {
            "hc-key": "us-nh",
            "value": 34
        },
        {
            "hc-key": "us-ky",
            "value": 35
        },
        {
            "hc-key": "us-oh",
            "value": 36
        },
        {
            "hc-key": "us-tn",
            "value": 37
        },
        {
            "hc-key": "us-wv",
            "value": 38
        },
        {
            "hc-key": "us-dc",
            "value": 39
        },
        {
            "hc-key": "us-la",
            "value": 40
        },
        {
            "hc-key": "us-fl",
            "value": 41
        },
        {
            "hc-key": "us-ga",
            "value": 42
        },
        {
            "hc-key": "us-sc",
            "value": 43
        },
        {
            "hc-key": "us-mn",
            "value": 44
        },
        {
            "hc-key": "us-mt",
            "value": 45
        },
        {
            "hc-key": "us-nd",
            "value": 46
        },
        {
            "hc-key": "us-az",
            "value": 47
        },
        {
            "hc-key": "us-ut",
            "value": 48
        },
        {
            "hc-key": "us-hi",
            "value": 49
        },
        {
            "hc-key": "us-ak",
            "value": 50
        },
        {
            "value": 51
        }];

    // Initiate the chart
    $('#container').highcharts('Map', {

        title : {
            text : ''
        },

        mapNavigation: {
            enabled: true,
            buttonOptions: {
                verticalAlign: 'bottom'
            }
        },
        
		tooltip: {
			formatter: function () {
				return '<b>' + this.point.name + '</b>' + ': ' + this.point.value;
			}
		},
        colorAxis: {
            min: 0
        },

        series : [{
            data: data,
            mapData: Highcharts.maps['countries/us/us-all'],
            joinBy: 'hc-key',
            states: {
                hover: {
                    color: '#BADA55'
                }
            },
            dataLabels: {
                enabled: true,
                format: '{point.value}'
            }
        }, {
            name: 'Separators',
            type: 'mapline',
            data: Highcharts.geojson(Highcharts.maps['countries/us/us-all'], 'mapline'),
            color: 'silver',
            showInLegend: false,
            enableMouseTracking: false
        }]
    });
});
</script>

app/views/home/index.html.erb
<h1>Recruit Map</h1>

<h2>Positions</h2>
<% @pos.each do |p| %>
	<%= link_to p, player_path(:id => p) %> |
<% end %>

<h2>Teams</h2>
<% @teams.each do |t| %>
	<%= link_to t, home_path(:id => t) %> |
<% end %>

<h2>Player Home State</h2>
<% @homeState.each do |h| %>
	<%= link_to h[0], hometown_index_path(:id => h[0]) %>(<%= h[1] %>) | 
<% end %><br />

<h2>Player Home City</h2>
<% @homeCity.each do |h| %>
	<%= link_to h[0], hometown_path(:id => h[0]) %>(<%= h[1] %>) | 
<% end %><br />

<%= render partial: 'mapScript' %>
<div id="container"></div>

app/views/home/show.html.erb
<div id="roster">
	<h1><%= params[:id] %></h1>
	<table cellspacing='0'> 
		<thead>
			<tr>
				<th>Player Name</th>
				<th>Position</th>
				<th>Hometown</th>
			</tr>
		</thead>
		<tbody>
			<% @playerList.each do |t| %>
			<tr>
				<td><%= t.name %></td>
				<td><%= t.pos %></td>
				<td><%= t.hometown %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/hometown/index.html.erb
<div id="roster">
	<h1>Players from <%= params[:id] %></h1>
	<table cellspacing='0'> 
		<thead>
			<tr>
				<th>Player Name</th>
				<th>Position</th>
				<th>Home City</th>
				<th>Team</th>
			</tr>
		</thead>
		<tbody>
			<% @players.each do |p| %>
			<tr>
				<td><%= p.name %></td>
				<td><%= p.pos %></td>
				<td><%= p.city %></td>
				<td><%= p.team %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/hometown/show.html.erb
<div id="roster">
	<h1>Players from <%= params[:id] %></h1>
	<table cellspacing='0'> 
		<thead>
			<tr>
				<th>Player Name</th>
				<th>Position</th>
				<th>Team</th>
			</tr>
		</thead>
		<tbody>
			<% @players.each do |p| %>
			<tr>
				<td><%= p.name %></td>
				<td><%= p.pos %></td>
				<td><%= p.team %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecruitMap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'highmaps' %>
  <%= javascript_include_tag 'us-all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', root_path %>
<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag import_players_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Upload" %>
<% end %>
<br />

<% if @players == 0 %>
	Please upload CSV file
<% else %>
	Records imported: <%= @players %><br /><br />
	<%= link_to 'Reset All', kill_players_url, :method => :delete %>
<% end %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Pos:</strong>
  <%= @player.pos %>
</p>

<p>
  <strong>Ht:</strong>
  <%= @player.ht %>
</p>

<p>
  <strong>Wt:</strong>
  <%= @player.wt %>
</p>

<p>
  <strong>Hometown:</strong>
  <%= @player.hometown %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @player.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @player.longitude %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team_id %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>